modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="cpmsvcc"
version="${mod_version}"
displayName="CPM SVC Compat"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cpmsvcc" #optional
credits="tom5454"
authors="tom5454"
description='''
A Customizable Player Models, Simple Voice Chat compat mod.
'''
[[dependencies.cpmsvcc]]
    modId="forge"
    mandatory=false
    type="optional"
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="neoforge"
    mandatory=false
    type="required"
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="minecraft"
    mandatory=true
    type="required"
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="voicechat"
    mandatory=true
    type="required"
    versionRange="[1.16.5-${voicechat_dependency},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="cpm"
    mandatory=true
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"