modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="cpmsvcc"
version="${mod_version}"
displayName="CPM SVC Compat"
logoFile="icon.png"
displayURL="https://www.curseforge.com/minecraft/mc-mods/cpmsvcc" #optional
credits="tom5454"
authors="tom5454"
description='''
A Customizable Player Models, Simple Voice Chat compat mod.
'''
[[dependencies.cpmsvcc]]
    modId="neoforge"
    type="required"
    versionRange="[20.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="voicechat"
    type="required"
    versionRange="[1.20.5-${voicechat_dependency},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cpmsvcc]]
    modId="cpm"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"